id: P000141
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །བསྟན་པ་དམ་པའི་ཆོས་ཀྱི་རིམ་པ་ཕྱེ་བ། །
  authors:
  - མཛད་པ་པོ། འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
  - sabche
  id: RDI-TOK-03-1
web_metadata:
  title:
    en: A Systematic Presentation of Dharma, the Teaching
    bo: བསྟན་པ་དམ་པའི་ཆོས་ཀྱི་རིམ་པར་ཕྱེ་བ།
  collection:
    en: Treasury of Knowledge–  Book 3
    bo: ཤེས་བྱ་ཀུན་ཁྱབ་མཛོད།–  དེབ། ༣
  author:
    en: Jamgon Kongtrul Lodro Thaye
    bo: འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
  pusblisher:
    en: Rigpe Dorje Institute
    bo: རིག་པའི་རྡོ་རྗེ་གཙུག་ལག་སློབ་ཉེར་ཁང་།
  sku: RDI-TOK-03-1
  category:
    en: Dharma Teaching
    bo: ཆོས་བསླབ་བྱ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: RDI-TOK-03-1.epub
  description:
    en: ཤེས་བྱ་ཀུན་ཁྱབ་མཛོད། གནས་གསུམ་པ།
    bo: ཤེས་བྱ་ཀུན་ཁྱབ་མཛོད། གནས་གསུམ་པ།
